"""Original printable missions. Web sources inform task formats only.

British Council, Increasing speaking in class (information gaps):
https://africa.teachingenglish.org.uk/skills/tips/increasing-speaking-class
British Council, Project work (learner-created products):
https://africa.teachingenglish.org.uk/classroom/activities/project-work
Accessed 2026-09-13. All scenarios, clues, diagrams and answers below are original.
"""

MISSIONS = {
    "revision": dict(
        title="The weekend club challenge", accent="#236B57", icon="tent",
        mission="Pack for the right trip",
        instruction="Read the three trip cards. Write A, B or C for each clue.",
        cards=[("A", "FOREST", "Friday | 4 people\nCamping by a lake\nBring a raincoat", "tent"),
               ("B", "ISLAND", "Sunday | 6 people\nSwimming in the sea\nBring a water bottle", "island"),
               ("C", "CITY", "Saturday | 8 people\nVisiting a museum\nBring a notebook", "museum")],
        clues=[("We can swim, and our group has six people.", "B"),
               ("Our trip is before Saturday. We need raincoats.", "A"),
               ("We are going to see old things, not go camping.", "C")],
        stretch="Choose a trip. Tell a partner what you are going to do.",
        pair_title="The missing trip plan",
        pair_rows=[("Meeting time", "08:30"), ("Meeting place", "School gate"),
                   ("Lunch", "Soup and bread"), ("Group size", "6 people")],
        ask="What time do we meet? Where do we meet? What is for lunch? How many people are there?",
        decision="Choose forest, island or city. Agree on an activity and one thing everyone has to bring.",
        frame="We are going to ... We can ... Everyone has to ...",
        sample="We are going to visit an island. We can swim. Everyone has to bring a water bottle.",
        product="OUR CLUB MESSAGE", draw="Draw your trip badge.",
        checklist=["a place", "an activity", "a rule"]),
    "u1": dict(
        title="Join the welcome team", accent="#246A87", icon="flag",
        mission="Who has the right event pass?",
        instruction="Read the passes. Write the correct person's name for each clue.",
        cards=[("A", "EREN", "Group leader\n09:00 | Hall\nChecks the names", "clipboard"),
               ("B", "MINA", "Guide\n09:30 | Gate\nHelps the visitors", "sign"),
               ("C", "ADA", "Flag carrier\n10:00 | Garden\nCarries the flag", "flag")],
        clues=[("Visitors need help at the gate. Who do they ask?", "Mina"),
               ("Who checks the names before half past nine?", "Eren"),
               ("Who takes the flag to the garden?", "Ada")],
        stretch="Choose a job. Say: I am a ... I usually ...",
        pair_title="Rebuild the celebration programme",
        pair_rows=[("Parade time", "09:15"), ("Speech place", "Hall"),
                   ("Group leader", "Eren"), ("Music time", "10:30")],
        ask="When is the parade? Where is the speech? Who is the group leader? When does the music start?",
        decision="Choose one welcome-team job each. Agree on two polite instructions for visitors.",
        frame="I can be the ... Please ... Don't ...",
        sample="I can be the guide. You can carry the flag. Please follow me. Don't run near the stage.",
        product="WELCOME TO OUR SCHOOL", draw="Design your team badge.",
        checklist=["two jobs", "a polite instruction", "a Don't instruction"]),
    "u2": dict(
        title="Study lab: usually or now?", accent="#73539D", icon="book",
        mission="Spot the change",
        instruction="Compare each pupil's routine with today. Write the person's name.",
        cards=[("A", "ADA", "USUALLY: reads silently\nNOW: reads aloud\nCards: 100", "book"),
               ("B", "EREN", "USUALLY: works alone\nNOW: works with a peer\nCards: 200", "people"),
               ("C", "MAYA", "USUALLY: writes a diary\nNOW: marks answers\nCards: 150", "clipboard")],
        clues=[("Who is reading aloud instead of silently?", "Ada"),
               ("Who is working with a peer and has 200 cards?", "Eren"),
               ("Who has one hundred and fifty cards?", "Maya")],
        stretch="Choose a pupil. Say one usually sentence and one now sentence.",
        pair_title="Find the missing study details",
        pair_rows=[("Meeting day", "Wednesday"), ("Number of cards", "150"),
                   ("Task number", "23rd"), ("Reader today", "Ada")],
        ask="When does the group meet? How many cards are there? Which task are we doing? Who is reading?",
        decision="Choose two useful study habits. Decide what you are doing first today. Check a detail with a tag.",
        frame="We usually ... Today we are ... We ..., don't we?",
        sample="We usually review words and read aloud. Today we are working in pairs. We share ideas, don't we?",
        product="MY STUDY DIARY", draw="Draw usually and now.",
        checklist=["two habits", "an action now", "a question tag"]),
    "u3": dict(
        title="Lost-property detectives", accent="#A0526C", icon="wallet",
        mission="Whose wallet is it?",
        instruction="Use the labels and lengths. Write a name for each clue.",
        cards=[("A", "LEO'S WALLET", "Length: 12 cm\n2 pockets\nA star on the front", "wallet"),
               ("B", "MAYA'S WALLET", "Length: 9 cm\n3 pockets\nA heart on the front", "wallet"),
               ("C", "NOOR'S WALLET", "Length: 15 cm\n1 pocket\nA circle on the front", "wallet")],
        clues=[("Whose wallet is the smallest of the three?", "Maya's"),
               ("Whose wallet is longer than Leo's?", "Noor's"),
               ("Whose wallet has two pockets and a star?", "Leo's")],
        stretch="Compare two wallets with longer than or shorter than.",
        pair_title="Return the missing belongings",
        pair_rows=[("Wallet owner", "Mina"), ("Bracelet owner", "Leo"),
                   ("Trainers owner", "Ada"), ("Necklace owner", "Noor")],
        ask="Whose wallet is this? Whose bracelet is this? Whose trainers are these? Whose necklace is this?",
        decision="Choose two wallets from A1 for a display. Compare them, then ask and answer a whose question.",
        frame="... is longer than ... Whose ... is this? It is ...",
        sample="Noor's wallet is longer than Leo's. Whose wallet is this? It is Leo's wallet.",
        product="LOST-PROPERTY NOTICE", draw="Sketch a labelled wallet.",
        checklist=["two belongings", "a comparison", "a whose question"]),
    "u4": dict(
        title="A family day to plan", accent="#9A642C", icon="house",
        mission="Which visit fits?",
        instruction="Your train arrives at 10:20. Each walk starts at the station. Read and decide.",
        cards=[("A", "DESIGN STUDIO", "Tour: 10:30\nWalk: 20 minutes\nMeet a designer", "pencil"),
               ("B", "FACTORY", "Tour: 11:00\nWalk: 15 minutes\nMeet an engineer", "factory"),
               ("C", "NEWS OFFICE", "Tour: 10:25\nWalk: 10 minutes\nMeet a reporter", "news")],
        clues=[("Which place can you reach before its tour starts?", "Factory / B"),
               ("Which job can you learn about on that visit?", "Engineer"),
               ("What time does that tour start?", "11:00")],
        stretch="Say an arrangement: We are visiting ... tomorrow.",
        pair_title="Complete the family agenda",
        pair_rows=[("Train departure", "09:40"), ("Tour start", "11:00"),
                   ("Aunt's job", "Designer"), ("Uncle's apartment", "2nd floor")],
        ask="When does the train leave? When does the tour start? What is our aunt's job? Which floor is it on?",
        decision="Plan a visit after the tour. Choose a place and decide what you can do yourselves.",
        frame="We are visiting ... The ... starts at ... We can ... ourselves.",
        sample="We are visiting our uncle. The tour starts at eleven. We can carry our bags ourselves.",
        product="OUR FAMILY AGENDA", draw="Draw a sign for your visit.",
        checklist=["an arrangement", "a timetable", "ourselves"]),
    "u5": dict(
        title="Follow the festival trail", accent="#2A7085", icon="music",
        mission="Read the festival map",
        instruction="Use the map. Left and right are as you see them on the page.",
        map=True,
        clues=[("What is between the park and the hall?", "Tram stop"),
               ("What is opposite the stage across Festival Street?", "Tram stop"),
               ("Walk from the library towards the cafe. What is in between?", "Stage")],
        stretch="Say where two places are. Use between or opposite.",
        pair_title="Rebuild yesterday's festival notes",
        pair_rows=[("Festival day", "Saturday"), ("Jazz show time", "16:00"),
                   ("Stage location", "Beside the library"), ("Transport", "By tram")],
        ask="When was the festival? What time was the jazz show? Where was the stage? Was your journey by tram or by car?",
        decision="Choose a show to visit next time. Agree on transport and explain why. Check one past detail with a tag.",
        frame="We plan to ... because ... The festival was ..., wasn't it?",
        sample="We plan to watch jazz. We can go by tram because the roads are busy. The festival was on Saturday, wasn't it?",
        product="MY FESTIVAL REVIEW", draw="Sketch a festival poster.",
        checklist=["a plan", "a reason", "a past question tag"]),
    "u6": dict(
        title="The culture-market passport", accent="#A25A32", icon="globe",
        mission="Collect the right passport stamps",
        instruction="These are imaginary school stalls. Match each clue to a stall letter.",
        cards=[("A", "ITALY", "Language: Italian\nServed a crispy appetiser\nPrepared 3 posters", "passport"),
               ("B", "SWEDEN", "Language: Swedish\nServed a sour dessert\nPrepared 2 posters", "passport"),
               ("C", "SPAIN", "Language: Spanish\nServed a spicy main course\nPrepared 4 posters", "passport")],
        clues=[("We tried a dessert and practised Swedish words.", "B"),
               ("We counted four posters and tasted a main course.", "C"),
               ("We enjoyed a crispy appetiser. Which stall was it?", "A")],
        stretch="Choose a stall. Say what you tried and which language you practised.",
        pair_title="Interview the culture-market team",
        pair_rows=[("Country presented", "Poland"), ("Language practised", "Polish"),
                   ("Posters prepared", "5"), ("Food served", "A homemade dessert")],
        ask="Which country did you present? Which language did you practise? How many posters did you prepare? What did you serve?",
        decision="Invent a fourth stall. Choose a country and a dish. Report what you served and what you didn't prepare.",
        frame="We presented ... We served ... We didn't prepare ...",
        sample="We presented France. We served a homemade dessert. We didn't prepare a main course.",
        product="MY CULTURE-MARKET REPORT", draw="Design a country stamp.",
        checklist=["a country", "two past actions", "a negative sentence"]),
    "u7": dict(
        title="The eco-camp mission", accent="#35744D", icon="leaf",
        mission="Rule, ban or choice?",
        instruction="Read the signs. Match each action to R (required), X (forbidden) or O (optional).",
        cards=[("R", "CAMP RULE", "Every camper has to\nbring a reusable\nwater bottle.", "bottle"),
               ("X", "PROTECT THE PATH", "Visitors mustn't\nleave any rubbish\nbeside the path.", "bin"),
               ("O", "YOUR CHOICE", "You don't have to\njoin the drawing club.\nYou can rest instead.", "pencil")],
        clues=[("Leave a plastic bag beside the path.", "X"),
               ("Bring your own reusable bottle.", "R"),
               ("Join the drawing club.", "O")],
        stretch="Explain why mustn't and don't have to mean different things.",
        pair_title="Rebuild the clean-up report",
        pair_rows=[("Activity", "Hiking"), ("Place", "Beside a river"),
                   ("Bottles collected", "14"), ("Equipment", "Gloves and reusable bags")],
        ask="What did you do? Where did you go? How many bottles did you collect? What did you take?",
        decision="Create a camp sign together: one required action, one forbidden action and one optional activity.",
        frame="You have to ... You mustn't ... You don't have to ...",
        sample="You have to follow the path. You mustn't leave rubbish. You don't have to join the drawing club.",
        product="OUR ECO-CAMP REPORT", draw="Design a camp sign.",
        checklist=["a required action", "a forbidden action", "an optional activity"]),
    "u8": dict(
        title="Future fair: mission control", accent="#57599F", icon="planet",
        mission="Plan, evidence or prediction?",
        instruction="Read the displays. Write A, B or C for each clue.",
        cards=[("A", "OUR PLAN", "We have decided:\nwe are going to make\na model of Mars.", "planet"),
               ("B", "LOOK NOW", "The model is falling\noff the desk! It is\ngoing to hit the floor.", "falling"),
               ("C", "OUR PREDICTION", "I think future schools\nwill use less energy.\nI cannot be certain.", "bulb")],
        clues=[("Which display uses something we can see now?", "B"),
               ("Which display describes a decision already made?", "A"),
               ("Which display gives an uncertain idea about the future?", "C")],
        stretch="Give your own plan and prediction. Begin the prediction with I think.",
        pair_title="Complete the future-fair plan",
        pair_rows=[("Fair day", "Thursday"), ("Model planet", "Saturn"),
                   ("Materials", "Old boxes"), ("Meeting place", "Science room")],
        ask="When is the fair? Which planet are we going to show? What are we going to use? Where are we going to meet?",
        decision="Design a useful invention for a future school. Agree on a plan and predict how it will help.",
        frame="We are going to make ... I think it will ... It will ..., won't it?",
        sample="We are going to make a solar lamp. I think it will save energy. It will help our school, won't it?",
        product="MY FUTURE SCHOOL", draw="Sketch your invention.",
        checklist=["an invention", "a going to plan", "a will prediction"]),
}
