"""Authored extra models and missing phrase examples for teaching decks."""
EXAMPLES = {
    "Clothes Verbs": [
        ("I *try on* a jacket before I buy it.", "Bir ceketi almadan önce denerim."),
        ("You *look* great in that shirt.", "O gömlekle harika görünüyorsun."),
        ("Designers *create* new clothes.", "Tasarımcılar yeni kıyafetler tasarlar.")],
    "Asking for Permission": [
        ("*Yes, you can.*", "Evet, yapabilirsin."), ("*Sure.*", "Tabii."),
        ("*Of course.*", "Elbette."), ("*No, you can't.*", "Hayır, yapamazsın."),
        ("*Sorry, not now.*", "Üzgünüm, şimdi olmaz.")],
    "Imperatives in Recipes": [
        ("*Stir* the sauce slowly.", "Sosu yavaşça karıştır."),
        ("*Pour* the milk into a bowl.", "Sütü bir kaseye dök."),
        ("*Serve* the soup hot.", "Çorbayı sıcak servis et.")],
    "Sequencing Words": [("*Next*, add the cheese.", "Sonra peyniri ekle.")],
    "On the Phone": [("This is Ece *speaking*.", "Ben Ece, konuşuyorum.")],
    "Giving Instructions": [
        ("*Open* your browser.", "Tarayıcını aç."),
        ("*Download* the worksheet.", "Çalışma kağıdını indir."),
        ("*Log in* to your account.", "Hesabına giriş yap.")],
    "Simple Past — Regular": [
        ("We *travelled* by train last summer.", "Geçen yaz trenle seyahat ettik."),
        ("I *enjoyed* the boat tour.", "Tekne turundan keyif aldım.")],
    "Simple Past — Irregular": [("I *bought* a souvenir for my sister.", "Kız kardeşime bir hediyelik eşya aldım.")],
    "Simple Present — Routines": [
        ("I *always* brush my teeth before bed.", "Yatmadan önce her zaman dişlerimi fırçalarım."),
        ("She *usually* listens to music after school.", "Okuldan sonra genellikle müzik dinler."),
        ("We *often* play basketball.", "Sık sık basketbol oynarız."),
        ("He *sometimes* goes to concerts.", "Bazen konserlere gider."),
        ("I *never* skip breakfast.", "Kahvaltıyı asla atlamam.")],
    "Predictions with will": [("The storm *may* reach our town tonight.", "Fırtına bu gece kasabamıza ulaşabilir.")],
    "If Clauses (Type 1)": [("*If* it rains, we *will* stay indoors.", "Yağmur yağarsa içeride kalacağız.")],
    "Giving Advice in a Disaster": [("You *should* keep an emergency bag ready.", "Bir acil durum çantasını hazır tutmalısın.")],
    "Preferences": [("I *would rather* cycle than drive.", "Araba kullanmaktansa bisiklete binmeyi tercih ederim.")],
    "How often ...?": [("*How often* do you go swimming?", "Ne sıklıkla yüzmeye gidersin?")],
    "How much / How many": [("*How many* eggs do we need?", "Kaç yumurtaya ihtiyacımız var?")],
    "Present Continuous": [("My brother *is talking* on the phone.", "Erkek kardeşim telefonda konuşuyor.")],
    "Internet Safety": [("*Don't* open messages from strangers.", "Yabancılardan gelen mesajları açma.")],
    "should / shouldn't": [("You *should* wear a helmet when you cycle.", "Bisiklete binerken kask takmalısın.")],
    "must / mustn't": [("You *mustn't* leave rubbish here.", "Buraya çöp bırakmamalısın.")],
    "Comparing Adventures": [("Rafting is *more exciting than* hiking.", "Rafting doğa yürüyüşünden daha heyecanlıdır.")],
    "have to / has to": [("My brother *has to* tidy his room.", "Erkek kardeşim odasını toplamak zorunda.")],
    "Accepting & Refusing Requests": [("*Of course.* I can help you.", "Elbette. Sana yardım edebilirim.")],
    "Accepting & Refusing": [("*I'd love to*, but I have to study.", "Çok isterim ama ders çalışmak zorundayım.")],
    "Passive Voice — Present": [("Glass *is recycled* in this factory.", "Bu fabrikada cam geri dönüştürülür.")],
    "Passive Voice — Past": [("The bridge *was built* in 1990.", "Köprü 1990 yılında inşa edildi.")],
    "Do you like ...?": [("*Do you like* reading comics?", "Çizgi roman okumayı sever misin?")],
    "Imperatives": [("*Open* your book, please.", "Lütfen kitabını aç.")],
    "Obligations — must / mustn't": [("We *must* listen to our teacher.", "Öğretmenimizi dinlemeliyiz.")],
    "Classroom Rules": [("*Raise* your hand before you speak.", "Konuşmadan önce elini kaldır.")],
    "have got / has got": [("She *has got* a red bag.", "Onun kırmızı bir çantası var.")],
    "There is / There are": [("*There are* two chairs in the room.", "Odada iki sandalye var.")],
    "What do/does ... look like?": [("She *has got* curly hair.", "Onun kıvırcık saçları var.")],
    "Simple Present — Positive": [("My sister *walks* to school.", "Kız kardeşim okula yürüyerek gider.")],
    "Present Continuous — -ing": [("We *are reading* a story now.", "Şimdi bir hikaye okuyoruz.")],
    "Simple Present": [("He *plays* football on Saturdays.", "Cumartesi günleri futbol oynar.")],
    "Possessive 's": [("This is Ece*'s* bicycle.", "Bu Ece'nin bisikleti.")],
    "Comparative Adjectives": [("An elephant is *bigger than* a lion.", "Bir fil bir aslandan daha büyüktür.")],
    "Superlative Adjectives": [("The giraffe is *the tallest* animal here.", "Zürafa buradaki en uzun hayvandır.")],
    "Expressing Ability — can / can't": [("A dolphin *can* swim very fast.", "Bir yunus çok hızlı yüzebilir.")],
    "Simple Future — be going to": [("We *are going to* travel by train next month.", "Gelecek ay trenle seyahat edeceğiz.")],
}

RULES = {
    "would you like to": "Kibar bir davet: *Would you like to + yalın fiil?*",
    "how about": "Bir etkinlik önerirken: *How about + fiil-ing?*",
    "let's": "Birlikte yapmayı önerirken: *Let's + yalın fiil.*",
    "why don't we": "Birlikte yapmayı önerirken: *Why don't we + yalın fiil?*",
    "a": "Sessiz sesle başlayan tekil, sayılabilen bir isimden önce *a* kullanılır.",
    "an": "Sesli sesle başlayan tekil, sayılabilen bir isimden önce *an* kullanılır.",
    "the": "Belirli, daha önce sözü edilen veya tek olan bir şeyi anlatırken *the* kullanılır.",
    "must": "Zorunluluk: *must + yalın fiil* (-meli / -malı).",
    "mustn't": "Yasak: *mustn't + yalın fiil* (yapılmaması gereken davranış).",
    "should": "Tavsiye: *should + yalın fiil* (-meli / -malı).",
    "shouldn't": "Olumsuz tavsiye: *shouldn't + yalın fiil*.",
    "have got": "I / You / We / They ile sahiplik: *have got*.",
    "has got": "He / She / It ile sahiplik: *has got*.",
    "there is": "Tekil bir şeyin varlığı: *There is + tekil isim*.",
    "there are": "Birden fazla şeyin varlığı: *There are + çoğul isim*.",
    "some": "Olumlu cümlelerde birkaç / biraz anlamında *some* kullanılır.",
    "any": "Olumsuz cümlelerde ve sorularda *any* kullanılır.",
    "can i": "İzin istemek için: *Can I + yalın fiil?*",
    "could you": "Kibar rica: *Could you + yalın fiil?*",
    "would you mind": "Kibar rica: *Would you mind + fiil-ing?*",
    "shall i": "Yardım teklif etmek için: *Shall I + yalın fiil?*",
}
